USE BD1d2b_2022
GO

CREATE USER Tester FOR LOGIN Tester
GRANT SELECT, UPDATE, INSERT, ALTER, DELETE, CONTROL ON SCHEMA::dbo TO Tester

USE master
GO
GRANT CREATE TABLE, CREATE DATABASE, CONTROL TO Tester
ALTER SERVER ROLE sysadmin ADD MEMBER [Tester];